### ISSUE TITLE
As a user, I want to be able to see the total rebate amount and total amount spent per day.

### ISSUE THREAD

**Issue by Xutherx** [andreaaa15/Super-Warehouse#2]

**Comment by andreaaa15** [comment]
As a user, I want to be able to see the total rebate amount and total amount spent per day.

Acceptance criteria:
Total rebate amount should be displayed
Total amount spent per day should be displayed
Buttons for total rebate amount and total amount spent per day can be clicked and will open a new window for each button
The data in the new window is correct

Done: 
Tests to read from the files and implement the output to GUI. On the GUI, there will be a button to calculate the total rebate amount. The total rebate amount will be displayed in a window which will pop up when the button for the total rebate amount is clicked. The GUI will also have another button for the total amount spent per day. Once the total amount spent per day button is clicked, a new window will pop up which shows the total amount spent per day. The information which pops up should be correct.

Tasks:
Function to calculate amount spent in year by customer and rebate, and update information in the file
Create a function to output 
Rebate and total amount spent will be member variables

Story Point:  3-4
